@startuml kompany_order_documents
!include ../style.plantuml

' lifeline definition
actor       "User"           as user
participant "Rawdata API"    as rdi

title Order documents from the kompany API


note over user
  For all requests you need
  to have a valid authentication
end note

' setup autonumber to use two segments (A.B)
' use autonumber inc [AB] to increase earch segment.
autonumber 1.1

' search company by name and  countryCode

user -> rdi    : Search for a company by Name and CountryCode
rdi -> user    : <b>200:</b> A list of matching companies

...

autonumber inc A

' get available documents for a specific company

user -> rdi    : With the subjectID from the search above\nrequest a list of available products / documents for the company
rdi -> user    : <b>200:</b> A list of available products for the requested company

...

autonumber inc A

' order a document


user -> rdi    : Order a document with the subjectID of the company and the SKU you want to oder
rdi -> user    : <b>200:</b> order ID

...

autonumber inc A

' get order status

user -> rdi    : Get status of the order

alt order succeeded

  rdi -> user : <b>200:</b> The order is ready

else order is not ready yet

  rdi -> user : <b>200:</b> The order did not fail, but is also not ready yet

else order failed

  rdi -> user : <b>200:</b> The order failed

end

...

autonumber inc A

' get the ordered document

user -> rdi : Request document

alt order is ready

  rdi -> user      : <b>404:</b> Document not found

else order is not ready

  rdi -> user      : <b>200:</b> The ordered document

end

...

@enduml
